version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pip==18.0
            sudo pip install pipenv==2018.7.1
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: generate docs
          command: pipenv run mkdocs build --clean --strict --verbose
      - store_artifacts:
          path: site
# Auto changelog collector
  github-changelog-generator:
    working_directory: ~/build
    docker: 
      - image: ferrarimarco/github-changelog-generator:1.14.3
    steps:
      - setup_remote_docker:
           version: 17.11.0-ce
      - run:
           name: Clone repo and Build changelog
           working_directory: ~/build
           command: |
             wget https://raw.githubusercontent.com/franklin-feingold/bids-specification-test/master/CHANGES.md
             cat ~/build/CHANGES.md
             github_changelog_generator --user franklin-feingold --project bids-specification-test --token ${CHANGE_TOKEN} --output TEST3.md --base /home/circleci/build/CHANGES.md --header-label Changelog --no-issues --no-issues-wo-labels --no-filter-by-milestone --no-compare-link --pr-label ""
             cat ~/build/TEST3.md
      - deploy:
           name: Changelog deployment
           working_directory: ~/build
           command: |
             git config credential.helper 'cache --timeout=120'
             git config user.email "franklin.feingold@gmail.com"
             git config user.name "franklin-feingold"
             git add TEST3.md
            #git commit -m "autobuild changelog"
            #git push -q https://${CHANGE_TOKEN}@github.com/franklin-feingold/bids-specification-test.git master          

workflows:
  version: 2
  search_build:
    jobs:
      - build
      - github-changelog-generator
